### ISSUE TITLE
minecraft hack

### ISSUE THREAD

**Issue by Indeeqs** [diegcrane/axis-external-minecraft-hack#2]
hi, can you do minecraft hack for launcher 1.16.3? just with one aim func?) pleeeaseee

**Comment by Indeeqs** [comment]
or say how can I do it on python or c++ not with mod java or version of java, I need dll hack, for minecraft NOT original launcher and I dont know how to do it(

**Comment by diegcrane** [comment]
U can make this work on 1.16 by changing the pattern and the offsets. Make the research urself :D

**Comment by Indeeqs** [comment]
can i inject your cheat in not original minecraft launcher like badlion not forge and optifine, just 1.16.3 minecraft launcher? or I need forge for inject?

**Comment by Nowno** [comment]
> can i inject your cheat in not original minecraft launcher like badlion not forge and optifine, just 1.16.3 minecraft launcher? or I need forge for inject?

voukamo notalo SCAM arkoma boumbalo bobo OBAMA maybe manobo baboudo cakoma litalo
