### ISSUE TITLE
didnt work with cheatbreaker

### ISSUE THREAD

**Issue by ramboi234** [diegcrane/axis-external-minecraft-hack#4]
when I use cheatbreaker client its said Minecraft version didn't supported, I use version 1.8.9 on cheatbreaker client,also If I use it on badlion can I got hwid banned even BAC off?

**Comment by diegcrane** [comment]
http://www.mediafire.com/file/owscjujzuo894se/CheatBreakerDev_Version.rar/file

**Comment by diegcrane** [comment]
use that cheatbreaker version. it doesnt work anymore on badlion

**Comment by ramboi234** [comment]
ah, most server didnt support minecraft version 1.7, thanks anyway just gonna use forge
